spring:
  cloud:
    gateway:
      routes:
        - id: service-transaction
          uri: lb://service-transaction
          predicates:
            - Path=/api-transaction/**
            - Header=token
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1

        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api-product/**
            - Header=token
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1

        - id: service-client
          uri: lb://service-client
          predicates:
            - Path=/api-client/**
            - Header=token
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1
